# Generated by Django 4.1.6 on 2023-02-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='name',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='query',
            name='term',
        ),
        migrations.AddField(
            model_name='query',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
