# Generated by Django 4.1.6 on 2023-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0002_rename_name_query_url_remove_query_term_query_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
