# Generated by Django 4.1.6 on 2023-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0003_urldata_delete_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
