# Generated by Django 4.1.6 on 2023-02-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0004_urldata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
