# Generated by Django 4.1.6 on 2023-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serach', '0005_alter_urldata_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='se',
            field=models.CharField(default='', max_length=255),
        ),
    ]
